These are the loading of the packages.

In [1]:
# import packages here
import pandas as pd
import numpy as np
from scipy import stats

These are the two data sets we were provided with from the Boston files. I have loaded them all for you guys using the packages that we learned (pandas). We are now ready to start cleaning!

In [2]:
# here is our loaded files
crime= pd.read_csv('crime - first six months.csv', engine='python')

In [3]:
new_colnames = [x.lower().replace(' ', '_') for x in crime.columns]
crime.columns= new_colnames
crime.head()

,incident_number,offense_code,offense_code_group,offense_description,district,reporting_area,shooting,occurred_on_date,year,month,day_of_week,hour,ucr_part,street,lat,long,location
0,I182070945,619,Larceny,LARCENY ALL OTHERS,D14,808,NaN,2018/9/2 13:00,2018,9,Sunday,13,Part One,LINCOLN ST,42.357791,-71.139371,"(42.35779134, -71.13937053)"
1,I182070941,3410,Towed,TOWED MOTOR VEHICLE,D4,151,NaN,2018/9/3 19:27,2018,9,Monday,19,Part Three,CAZENOVE ST,42.346589,-71.072429,"(42.34658879, -71.07242943)"
2,I182070940,3114,Investigate Property,INVESTIGATE PROPERTY,D4,272,NaN,2018/9/3 21:16,2018,9,Monday,21,Part Three,NEWCOMB ST,42.334182,-71.078664,"(42.33418175, -71.07866441)"
3,I182070938,3114,Investigate Property,INVESTIGATE PROPERTY,B3,421,NaN,2018/9/3 21:05,2018,9,Monday,21,Part Three,DELHI ST,42.275365,-71.090361,"(42.27536542, -71.09036101)"
4,I182070936,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,C11,398,NaN,2018/9/3 21:09,2018,9,Monday,21,Part Three,TALBOT AVE,42.290196,-71.071590,"(42.29019621, -71.07159012)"

In [4]:
crime['shooting'] = crime['shooting'].fillna(False)

In [5]:
crime.head()

,incident_number,offense_code,offense_code_group,offense_description,district,reporting_area,shooting,occurred_on_date,year,month,day_of_week,hour,ucr_part,street,lat,long,location
0,I182070945,619,Larceny,LARCENY ALL OTHERS,D14,808,False,2018/9/2 13:00,2018,9,Sunday,13,Part One,LINCOLN ST,42.357791,-71.139371,"(42.35779134, -71.13937053)"
1,I182070941,3410,Towed,TOWED MOTOR VEHICLE,D4,151,False,2018/9/3 19:27,2018,9,Monday,19,Part Three,CAZENOVE ST,42.346589,-71.072429,"(42.34658879, -71.07242943)"
2,I182070940,3114,Investigate Property,INVESTIGATE PROPERTY,D4,272,False,2018/9/3 21:16,2018,9,Monday,21,Part Three,NEWCOMB ST,42.334182,-71.078664,"(42.33418175, -71.07866441)"
3,I182070938,3114,Investigate Property,INVESTIGATE PROPERTY,B3,421,False,2018/9/3 21:05,2018,9,Monday,21,Part Three,DELHI ST,42.275365,-71.090361,"(42.27536542, -71.09036101)"
4,I182070936,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,C11,398,False,2018/9/3 21:09,2018,9,Monday,21,Part Three,TALBOT AVE,42.290196,-71.071590,"(42.29019621, -71.07159012)"

In [6]:
crime['district'] = crime['district'].fillna('N/A')

In [7]:
crime['reporting_area'] = crime['reporting_area'].replace(' ','N/A')

In [8]:
crime['ucr_part'] = crime['ucr_part'].fillna('N/A')

In [9]:
crime['street'] = crime['street'].fillna('N/A')

In [11]:
crime['lat'] = crime['lat'].fillna('N/A')
crime['long'] = crime['long'].fillna('N/A')

In [13]:
crime.to_csv(r"C:\Users\quant\Desktop\Digital Humanities\NaN_processed.csv")

In [12]:
crime.head(20)

,incident_number,offense_code,offense_code_group,offense_description,district,reporting_area,shooting,occurred_on_date,year,month,day_of_week,hour,ucr_part,street,lat,long,location
0,I182070945,619,Larceny,LARCENY ALL OTHERS,D14,808,False,2018/9/2 13:00,2018,9,Sunday,13,Part One,LINCOLN ST,42.3578,-71.1394,"(42.35779134, -71.13937053)"
1,I182070941,3410,Towed,TOWED MOTOR VEHICLE,D4,151,False,2018/9/3 19:27,2018,9,Monday,19,Part Three,CAZENOVE ST,42.3466,-71.0724,"(42.34658879, -71.07242943)"
2,I182070940,3114,Investigate Property,INVESTIGATE PROPERTY,D4,272,False,2018/9/3 21:16,2018,9,Monday,21,Part Three,NEWCOMB ST,42.3342,-71.0787,"(42.33418175, -71.07866441)"
3,I182070938,3114,Investigate Property,INVESTIGATE PROPERTY,B3,421,False,2018/9/3 21:05,2018,9,Monday,21,Part Three,DELHI ST,42.2754,-71.0904,"(42.27536542, -71.09036101)"
4,I182070936,3820,Motor Vehicle Accident Response,M/V ACCIDENT INVOLVING PEDESTRIAN - INJURY,C11,398,False,2018/9/3 21:09,2018,9,Monday,21,Part Three,TALBOT AVE,42.2902,-71.0716,"(42.29019621, -71.07159012)"
5,I182070933,724,Auto Theft,AUTO THEFT,B2,330,False,2018/9/3 21:25,2018,9,Monday,21,Part One,NORMANDY ST,42.3061,-71.0827,"(42.30607218, -71.08273260)"
6,I182070932,3301,Verbal Disputes,VERBAL DISPUTE,B2,584,False,2018/9/3 20:39,2018,9,Monday,20,Part Three,LAWN ST,42.327,-71.1056,"(42.32701648, -71.10555088)"
7,I182070931,301,Robbery,ROBBERY - STREET,C6,177,False,2018/9/3 20:48,2018,9,Monday,20,Part One,MASSACHUSETTS AVE,42.3315,-71.0709,"(42.33152148, -71.07085307)"
8,I182070929,3301,Verbal Disputes,VERBAL DISPUTE,C11,364,False,2018/9/3 20:38,2018,9,Monday,20,Part Three,LESLIE ST,42.2951,-71.0586,"(42.29514664, -71.05860832)"
9,I182070928,3301,Verbal Disputes,VERBAL DISPUTE,C6,913,False,2018/9/3 19:55,2018,9,Monday,19,Part Three,OCEAN VIEW DR,42.3196,-71.0403,"(42.31957856, -71.04032766)"
10,I182070927,3114,Investigate Property,INVESTIGATE PROPERTY,C6,936,False,2018/9/3 20:19,2018,9,Monday,20,Part Three,DALESSIO CT,42.3401,-71.0534,"(42.34011469, -71.05339029)"
11,I182070923,3108,Fire Related Reports,"FIRE REPORT - HOUSE, BUILDING, ETC.",D4,139,False,2018/9/3 19:58,2018,9,Monday,19,Part Three,MARLBOROUGH ST,42.3504,-71.0879,"(42.35038760, -71.08785290)"
12,I182070922,2647,Other,THREATS TO DO BODILY HARM,B3,429,False,2018/9/3 20:39,2018,9,Monday,20,Part Two,WOODROW AVE,42.2865,-71.0871,"(42.28647012, -71.08714661)"
13,I182070921,3201,Property Lost,PROPERTY - LOST,B3,469,False,2018/9/2 14:00,2018,9,Sunday,14,Part Three,MULVEY ST,42.2792,-71.0967,"(42.27924052, -71.09667382)"
14,I182070920,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,N/A,N/A,False,2018/9/3 19:43,2018,9,Monday,19,Part Three,N/A,42.3529,-71.0738,"(42.35287456, -71.07382970)"
15,I182070919,3301,Verbal Disputes,VERBAL DISPUTE,C11,341,False,2018/9/3 18:52,2018,9,Monday,18,Part Three,STONEHURST ST,42.3053,-71.0668,"(42.30526428, -71.06683755)"
16,I182070918,3305,Assembly or Gathering Violations,DEMONSTRATIONS/RIOT,D4,130,False,2018/9/3 17:00,2018,9,Monday,17,Part Three,HUNTINGTON AVE,42.3486,-71.0777,"(42.34857652, -71.07772012)"
17,I182070917,2647,Other,THREATS TO DO BODILY HARM,B2,901,False,2018/9/3 19:52,2018,9,Monday,19,Part Two,HORADAN WAY,42.3337,-71.0967,"(42.33371742, -71.09665806)"
18,I182070915,614,Larceny From Motor Vehicle,LARCENY THEFT FROM MV - NON-ACCESSORY,B2,181,False,2018/9/2 18:00,2018,9,Sunday,18,Part One,SHIRLEY ST,42.3257,-71.0682,"(42.32569490, -71.06816778)"
19,I182070913,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,N/A,N/A,False,2018/9/3 18:46,2018,9,Monday,18,Part Three,WOLCOTT,-1,-1,"(-1.00000000, -1.00000000)"

In [21]:
crime.loc[14,'reporting_area']

' '